version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: payment_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_gateway
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - payment-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: payment_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8088:80"
    depends_on:
      - postgres
    networks:
      - payment-net


  adminer:
      image: adminer
      container_name: payment_adminer
      restart: always
      ports:
        - "8089:8080"
      depends_on:
        - postgres
      networks:
        - payment-net


volumes:
  pgdata:

networks:
  payment-net:
