version: "3.8"

services:

  # ---------- DATABASE ----------
  postgres:
    image: postgres:15
    container_name: payment_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_gateway
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - payment-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: payment_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8088:80"
    depends_on:
      - postgres
    networks:
      - payment-net

  adminer:
    image: adminer
    container_name: payment_adminer
    restart: always
    ports:
      - "8089:8080"
    depends_on:
      - postgres
    networks:
      - payment-net

  redis:
    image: redis:7
    container_name: payment_redis
    ports:
      - "6379:6379"
    networks:
      - payment-net

  # ---------- KAFKA ----------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - payment-net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - payment-net

  # ---------- APPLICATION SERVICES ----------
  merchant:
    image: ibrahimshammaz11/merchant:1.0
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
      - kafka
    networks:
      - payment-net

  payment:
    image: ibrahimshammaz11/payment:1.0
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
      - kafka
      - merchant
    networks:
      - payment-net

  processor:
    image: ibrahimshammaz11/processor:1.0
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka
      - payment
    networks:
      - payment-net

  mockbank:
    image: ibrahimshammaz11/mockbank:1.0
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - payment-net

  notification:
    image: ibrahimshammaz11/notification:1.0
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka
      - merchant
    networks:
      - payment-net

volumes:
  pgdata:

networks:
  payment-net:
