version: "3.8"

services:

  # ---------- DATABASE ----------
  postgres:
    image: postgres:15
    container_name: payment_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_gateway
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - payment-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: payment_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8088:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - payment-net

  adminer:
    image: adminer
    container_name: payment_adminer
    restart: always
    ports:
      - "8089:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - payment-net

  redis:
    image: redis:7
    container_name: payment_redis
    ports:
      - "6379:6379"
    networks:
      - payment-net

  # ---------- KAFKA ----------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: payment_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - payment-net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: payment_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - payment-net
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5

  # ---------- APPLICATION SERVICES ----------
  merchant:
    image: ibrahimshammaz11/merchant:1.0
    container_name: payment_merchant
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment_gateway
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - payment-net

  payment:
    image: ibrahimshammaz11/payment:1.0
    container_name: payment_service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment_gateway
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      merchant:
        condition: service_started
    networks:
      - payment-net

  processor:
    image: ibrahimshammaz11/processor:1.0
    container_name: payment_processor
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
      payment:
        condition: service_started
    networks:
      - payment-net

  mockbank:
    image: ibrahimshammaz11/mockbank:1.0
    container_name: payment_mockbank
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - payment-net

  notification:
    image: ibrahimshammaz11/notification:1.0
    container_name: payment_notification
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
      merchant:
        condition: service_started
    networks:
      - payment-net

volumes:
  pgdata:

networks:
  payment-net:
